import { describe, expect, it } from 'vitest'
import { compile } from '../compile.js'
import { Graph } from '../graph.js'
import type { ModuleDef, Processor, ProcessorVoice, Registry } from '../types.js'
import { MIDI_MODULE } from './midi.js'
import { CHORD_PLAYER_LANES, CHORD_PLAYER_MODULE, ChordPlayerProcessor } from './chord-player.js'

const FRAMES = 8
const constant = (value: number, frames = FRAMES) => new Float32Array(frames).fill(value)

function params(over: Record<string, number> = {}) {
  return CHORD_PLAYER_MODULE.params.map((param) => constant(over[param.id] ?? param.default))
}

function generated(
  roots: number[],
  over: Record<string, number> = {},
  customScale?: number[],
): number[] {
  const voices = roots.length * CHORD_PLAYER_LANES
  const shared: Record<string, unknown> = {}
  const result: number[] = []
  for (let source = 0; source < roots.length; source++) {
    for (let lane = 0; lane < CHORD_PLAYER_LANES; lane++) {
      const context: ProcessorVoice = {
        voice: source * CHORD_PLAYER_LANES + lane,
        sourceVoice: source,
        lane,
        lanes: CHORD_PLAYER_LANES,
        voices,
        shared,
      }
      const processor = new ChordPlayerProcessor(44100, {}, 'chord', {
        get: (slot) => slot === 'customScale' && customScale
          ? Float32Array.from(customScale)
          : undefined,
      }, context)
      const out = [new Float32Array(FRAMES), new Float32Array(FRAMES), new Float32Array(FRAMES)]
      processor.process(
        [constant(roots[source] / 12), constant(1), constant(0.75)],
        out,
        params(over),
        FRAMES,
      )
      if (out[1][0] >= 0.5) result.push(out[0][0] * 12)
    }
  }
  return result
}

const close = (actual: number[], expected: number[]) => {
  expect(actual).toHaveLength(expected.length)
  expected.forEach((value, index) => expect(actual[index]).toBeCloseTo(value))
}

describe('the Chord Player', () => {
  it('builds tertian chords from corrected scale notes', () => {
    close(generated([0]), [0, 4, 7])
    close(generated([2]), [2, 5, 9])
    // F# ties between F and G in C major, so the chord roots on the lower note.
    close(generated([6]), [5, 9, 12])
  })

  it('supports one through five generated notes', () => {
    close(generated([0], { notes: 1 }), [0])
    close(generated([0], { notes: 5 }), [0, 4, 7, 11, 14])
  })

  it('inverts and opens the generated structure', () => {
    close(generated([0], { notes: 4, inversion: 1 }), [4, 7, 11, 12])
    close(generated([0], { notes: 4, inversion: 2 }), [-5, -1, 0, 4])
    close(generated([0], { notes: 4, inversion: 3 }), [-1, 0, 4, 7])
    close(generated([0], { notes: 3, open: 1 }), [0, 7, 16])
  })

  it('uses all eight lanes when every addition is active', () => {
    close(generated([0], { notes: 5, octDown: 1, octUp: 1, color: 1 }), [-12, 0, 4, 7, 11, 12, 14, 21])
  })

  it('moves duplicate additions another octave away', () => {
    close(generated([0], { notes: 1, octUp: 1, octDown: 1 }), [-12, 0, 12])
    close(generated([0], { notes: 4, inversion: 1, octUp: 1 }), [4, 7, 11, 12, 24])
  })

  it('alters a major third to minor and a minor third to major', () => {
    close(generated([0], { alter: 1 }), [0, 3, 7])
    close(generated([0], { scale: 1, alter: 1 }), [0, 4, 7])
  })

  it('preserves pitch bend after scale correction', () => {
    close(generated([6.25]), [5.25, 9.25, 12.25])
  })

  it('reads the portable custom scale and falls back safely when it is empty', () => {
    const wholeTone = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
    close(generated([1], { scale: 13 }, wholeTone), [0, 4, 8])
    close(generated([0], { scale: 13 }, Array(12).fill(0)), [0, 4, 7])
  })

  it('suppresses coincident notes generated by simultaneously played roots', () => {
    // C major and E minor share E and B. Each pitch is emitted once across the shared node state.
    close(generated([0, 4]), [0, 4, 7, 11])
  })

  it('declares the full eight-lane note transform', () => {
    expect(CHORD_PLAYER_MODULE.voiceExpansion).toBe(8)
    expect(CHORD_PLAYER_MODULE.inlets.map((port) => port.id)).toEqual(['pitch', 'gate', 'velocity'])
    expect(CHORD_PLAYER_MODULE.outlets.map((port) => port.id)).toEqual(['pitch', 'gate', 'velocity'])
  })
})

class CaptureProcessor implements Processor {
  static seen: number[] = []

  process(inlets: Float32Array[], _outlets: Float32Array[], _params: Float32Array[], _frames: number): void {
    if (inlets[1][0] >= 0.5) CaptureProcessor.seen.push(inlets[0][0] * 12)
  }
}

const CAPTURE: ModuleDef = {
  type: 'capture',
  version: 1,
  name: 'Capture',
  inlets: [
    { id: 'pitch', name: 'Pitch' },
    { id: 'gate', name: 'Gate' },
    { id: 'velocity', name: 'Velocity' },
  ],
  outlets: [],
  params: [],
  processor: CaptureProcessor,
}

it('expands into independent downstream voices through the compiled Graph', () => {
  const registry: Registry = {
    midi: MIDI_MODULE,
    'chord-player': CHORD_PLAYER_MODULE,
    capture: CAPTURE,
  }
  const patch = {
    voices: 1,
    modules: [
      { id: 'm', type: 'midi' },
      { id: 'c', type: 'chord-player' },
      { id: 'take', type: 'capture' },
    ],
    cables: [
      { from: ['m', 'pitch'] as [string, string], to: ['c', 'pitch'] as [string, string] },
      { from: ['m', 'gate'] as [string, string], to: ['c', 'gate'] as [string, string] },
      { from: ['m', 'velocity'] as [string, string], to: ['c', 'velocity'] as [string, string] },
      { from: ['c', 'pitch'] as [string, string], to: ['take', 'pitch'] as [string, string] },
      { from: ['c', 'gate'] as [string, string], to: ['take', 'gate'] as [string, string] },
      { from: ['c', 'velocity'] as [string, string], to: ['take', 'velocity'] as [string, string] },
    ],
  }
  const plan = compile(patch, registry)
  expect(plan.nodes.find((node) => node.id === 'c')?.voices).toBe(8)
  expect(plan.nodes.find((node) => node.id === 'take')?.voices).toBe(8)

  const graph = new Graph(44100, FRAMES, {
    midi: MIDI_MODULE.processor,
    'chord-player': CHORD_PLAYER_MODULE.processor,
    capture: CAPTURE.processor,
  }, {})
  graph.setPlan(plan)
  graph.setParam(plan.slots.m.note, 36, 0)
  graph.setParam(plan.slots.m.gate, 1, 0)
  graph.setParam(plan.slots.m.velocity, 1, 0)
  CaptureProcessor.seen = []
  graph.process([new Float32Array(FRAMES), new Float32Array(FRAMES)])
  close(CaptureProcessor.seen, [0, 4, 7])
})
